### ISSUE TITLE
crane command is failing

### ISSUE THREAD

**Issue by anniepamela2020** [thesecuresoftwarefactory/ssf#97] opened 2021-12-08 17:18 UTC
Current behavior
----------------

I have an issue with crane ls "IMAGE_URL" .

```
crane ls "${IMAGE_URL}"
Error: reading tags for localhost:8888: parsing repo "localhost:8888": repository can only contain the runes `abcdefghijklmnopqrstuvwxyz0123456789_-./`: localhost:8888
``` 

Expected Behavior
-----------------

crane should output informations about my image.

Possible Solution
-----------------

Steps to Reproduce
------------------

1.
2.
3.

Context
-------

Your Environment
----------------

```
(replace the example below with the script output)
Last commit:
  d6d7647 Alternate approach for internal minikube OCI registry  (HEAD -> github-templates, upstream/main, upstream/HEAD, main)
Kubernetes:
  Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-11-17T15:41:42Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"darwin/arm64"}
Tekton:
  Client version: 0.21.0
```

**Comment by bradbeck** [comment] 2021-12-08 17:43
The documentation probably needs to be adjusted for the differences between the examples (`buildpacks` & `imm-tutorial`).

The `README.md`'s for those should still be good.

The pipeline runs are slightly different between `buildpacks` and `ibm-tutorial`, so the query to get the output image is slightly different.

For `buildpacks` it’s:
```
tkn pr describe --last -o jsonpath='{.spec.params[?(@.name=="APP_IMAGE")].value}'
```
whereas for `ibm-tutorial` it’s:
```
tkn pr describe --last -o jsonpath='{.spec.params[?(@.name=="imageUrl")].value}'
```
In fact the `ibm-tutorial` actually stores the image tag in a separate location too:
```
tkn pr describe --last -o jsonpath='{.spec.params[?(@.name=="imageTag")].value}'
```

**Comment by maorkuriel** [comment] 2021-12-09 12:51
I also have an issue with the Crane command.
But in my case, it doesn't fail with an error message. It just hangs. 
I aborted it after 1 min.

**Comment by bradbeck** [comment] 2021-12-09 14:59
> I also have an issue with the Crane command. But in my case, it doesn't fail with an error message. It just hangs. I aborted it after 1 min.
> 
> When I run the crane command with -v I see 2021/12/09 14:56:23 <-- net/http: TLS handshake timeout GET https://localhost:8888/v2/ (10.002149875s) 2021/12/09 14:56:23 --> GET http://localhost:8888/v2/ 2021/12/09 14:56:23 GET /v2/ HTTP/1.1 Host: localhost:8888 User-Agent: crane/0.6.0 go-containerregistry/(devel) Accept-Encoding: gzip

@maorkuriel Are you able to reliably reproduce this issue? If so, can you please provide the steps used to reproduce it so we can better diagnose the issue?

**Comment by maorkuriel** [comment] 2021-12-09 17:48
> > I also have an issue with the Crane command. But in my case, it doesn't fail with an error message. It just hangs. I aborted it after 1 min.
> > When I run the crane command with -v I see 2021/12/09 14:56:23 <-- net/http: TLS handshake timeout GET https://localhost:8888/v2/ (10.002149875s) 2021/12/09 14:56:23 --> GET http://localhost:8888/v2/ 2021/12/09 14:56:23 GET /v2/ HTTP/1.1 Host: localhost:8888 User-Agent: crane/0.6.0 go-containerregistry/(devel) Accept-Encoding: gzip
> 
> @maorkuriel Are you able to reliably reproduce this issue? If so, can you please provide the steps used to reproduce it so we can better diagnose the issue?

Hi @bradbeck ,
Sorry for not providing the steps, I followed the steps from the quick start page https://thesecuresoftwarefactory.github.io/ssf/docs/getting-started/quick-start/
I didn't run the 2nd step - make registry-proxy ( it was marked as optional so I skipped it) I plan to do another run on Sunday, this time I will include the 2nd step.
 I will update you on the results.

**Comment by maorkuriel** [comment] 2021-12-12 12:13
@bradbeck, when I run the make registry-proxy, the Crane command works as expected.
The optional comment on the 2nd step needs to be removed as it might confuse users.
IMHO we need to add another step and mark it as optional. The step will be using your own registry.

**Comment by maorkuriel** [comment] 2021-12-16 09:38
Hi @bradbeck 
I just ran the latest version of the SSF and the Crane command is failing again.

crane ls "${IMAGE_URL}"

Error: reading tags for localhost:8888: parsing repo "localhost:8888": repository can only contain the runes `abcdefghijklmnopqrstuvwxyz0123456789_-./`: localhost:8888

**Comment by bradbeck** [comment] 2021-12-16 13:16
> 

What does the following return for you?
```bash
tkn pr describe --last -o jsonpath='{.spec.params}'
```

**Comment by maorkuriel** [comment] 2021-12-16 13:25
```
tkn pr describe --last -o jsonpath='{.spec.params}'

[{"name":"gitUrl","value":"https://github.com/IBM/tekton-tutorial"},{"name":"gitRevision","value":"beta-update"},{"name":"pathToYamlFile","value":"kubernetes/picalc.yaml"},{"name":"imageUrl","value":"registry.kube-system.svc.cluster.local/citi/picalc"},{"name":"imageTag","value":"1.0"}]%

```

**Comment by bradbeck** [comment] 2021-12-16 13:54
> tkn pr describe --last -o jsonpath='{.spec.params}'
> 
> [{"name":"gitUrl","value":"https://github.com/IBM/tekton-tutorial"},{"name":"gitRevision","value":"beta-update"},{"name":"pathToYamlFile","value":"kubernetes/picalc.yaml"},{"name":"imageUrl","value":"registry.kube-system.svc.cluster.local/citi/picalc"},{"name":"imageTag","value":"1.0"}]%

Ok, that looks good. Try the following:
```bash
IMAGE_URL=$(tkn pr describe --last -o jsonpath='{.spec.params[?(@.name=="imageUrl")].value}')
export IMAGE_URL=localhost:8888${IMAGE_URL#"registry.kube-system.svc.cluster.local"}
export IMAGE_TAG=$(tkn pr describe --last -o jsonpath='{.spec.params[?(@.name=="imageTag")].value}')
export DOCKER_IMG="${IMAGE_URL}:${IMAGE_TAG}"

crane ls "${IMAGE_URL}"
```

In the above, `IMAGE_URL` should be `localhost:8888/citi/picalc`

**Comment by maorkuriel** [comment] 2021-12-16 14:12
Here is the output

```
❯ IMAGE_URL=$(tkn pr describe --last -o jsonpath='{.spec.params[?(@.name=="imageUrl")].value}')
export IMAGE_URL=localhost:8888/citi/picalc${IMAGE_URL#"registry.kube-system.svc.cluster.local"}
export IMAGE_TAG=$(tkn pr describe --last -o jsonpath='{.spec.params[?(@.name=="imageTag")].value}')
export DOCKER_IMG="${IMAGE_URL}:${IMAGE_TAG}"

~
❯ crane ls "${IMAGE_URL}"

Error: reading tags for localhost:8888/citi/picalc/citi/picalc: Get "https://localhost:8888/v2/": dial tcp [::1]:8888: connect: connection refused; Get "http://localhost:8888/v2/": dial tcp [::1]:8888: connect: connection refused

~
❯ crane ls "${IMAGE_URL}"

Error: reading tags for localhost:8888/citi/picalc/citi/picalc: GET http://localhost:8888/v2/citi/picalc/citi/picalc/tags/list?n=1000: NAME_UNKNOWN: repository name not known to registry; map[name:citi/picalc/citi/picalc]
```

**Comment by bradbeck** [comment] 2021-12-16 14:16
> Here is the output
> 
> ```
> ❯ IMAGE_URL=$(tkn pr describe --last -o jsonpath='{.spec.params[?(@.name=="imageUrl")].value}')
> export IMAGE_URL=localhost:8888/citi/picalc${IMAGE_URL#"registry.kube-system.svc.cluster.local"}
> export IMAGE_TAG=$(tkn pr describe --last -o jsonpath='{.spec.params[?(@.name=="imageTag")].value}')
> export DOCKER_IMG="${IMAGE_URL}:${IMAGE_TAG}"
> 
> ~
> ❯ crane ls "${IMAGE_URL}"
> 
> Error: reading tags for localhost:8888/citi/picalc/citi/picalc: Get "https://localhost:8888/v2/": dial tcp [::1]:8888: connect: connection refused; Get "http://localhost:8888/v2/": dial tcp [::1]:8888: connect: connection refused
> 
> ~
> ❯ crane ls "${IMAGE_URL}"
> 
> Error: reading tags for localhost:8888/citi/picalc/citi/picalc: GET http://localhost:8888/v2/citi/picalc/citi/picalc/tags/list?n=1000: NAME_UNKNOWN: repository name not known to registry; map[name:citi/picalc/citi/picalc]
> ```
You don't need the extra `/citi/picalc` in the `export IMAGE_URL=...` line. The following as written should work:
```bash
IMAGE_URL=$(tkn pr describe --last -o jsonpath='{.spec.params[?(@.name=="imageUrl")].value}')
export IMAGE_URL=localhost:8888${IMAGE_URL#"registry.kube-system.svc.cluster.local"}
export IMAGE_TAG=$(tkn pr describe --last -o jsonpath='{.spec.params[?(@.name=="imageTag")].value}')
export DOCKER_IMG="${IMAGE_URL}:${IMAGE_TAG}"

crane ls "${IMAGE_URL}"
```
My note earlier was to highlight that crane should be trying to list `localhost:8888/citi/picalc`.

**Comment by maorkuriel** [comment] 2021-12-16 14:24
My first run was without the `/citi/picalc`   I added it on my 2nd run, just to ensure that I cover all the bases.

Here is the output:

```
~
❯ IMAGE_URL=$(tkn pr describe --last -o jsonpath='{.spec.params[?(@.name=="imageUrl")].value}')
export IMAGE_URL=localhost:8888${IMAGE_URL#"registry.kube-system.svc.cluster.local"}
export IMAGE_TAG=$(tkn pr describe --last -o jsonpath='{.spec.params[?(@.name=="imageTag")].value}')
export DOCKER_IMG="${IMAGE_URL}:${IMAGE_TAG}"

crane ls "${IMAGE_URL}"
Error: reading tags for localhost:8888/citi/picalc: GET http://localhost:8888/v2/citi/picalc/tags/list?n=1000: NAME_UNKNOWN: repository name not known to registry; map[name:citi/picalc]

~
❯ IMAGE_URL=$(tkn pr describe --last -o jsonpath='{.spec.params[?(@.name=="imageUrl")].value}')
export IMAGE_URL=localhost:8888${IMAGE_URL#"registry.kube-system.svc.cluster.local"}
export IMAGE_TAG=$(tkn pr describe --last -o jsonpath='{.spec.params[?(@.name=="imageTag")].value}')
export DOCKER_IMG="${IMAGE_URL}:${IMAGE_TAG}"

~
❯ crane ls "${IMAGE_URL}"

Error: reading tags for localhost:8888/citi/picalc: GET http://localhost:8888/v2/citi/picalc/tags/list?n=1000: NAME_UNKNOWN: repository name not known to registry; map[name:citi/picalc]

~
❯ crane ls localhost:8888/citi/picalc
```

Error: reading tags for localhost:8888/citi/picalc: GET http://localhost:8888/v2/citi/picalc/tags/list?n=1000: NAME_UNKNOWN: repository name not known to registry; map[name:citi/picalc]

**Comment by bradbeck** [comment] 2021-12-16 14:33
> My first run was without the `/citi/picalc` I added it on my 2nd run, just to ensure that I cover all the bases.
> 
> Here is the output:
> 
> ```
> ~
> ❯ IMAGE_URL=$(tkn pr describe --last -o jsonpath='{.spec.params[?(@.name=="imageUrl")].value}')
> export IMAGE_URL=localhost:8888${IMAGE_URL#"registry.kube-system.svc.cluster.local"}
> export IMAGE_TAG=$(tkn pr describe --last -o jsonpath='{.spec.params[?(@.name=="imageTag")].value}')
> export DOCKER_IMG="${IMAGE_URL}:${IMAGE_TAG}"
> 
> crane ls "${IMAGE_URL}"
> Error: reading tags for localhost:8888/citi/picalc: GET http://localhost:8888/v2/citi/picalc/tags/list?n=1000: NAME_UNKNOWN: repository name not known to registry; map[name:citi/picalc]
> 
> ~
> ❯ IMAGE_URL=$(tkn pr describe --last -o jsonpath='{.spec.params[?(@.name=="imageUrl")].value}')
> export IMAGE_URL=localhost:8888${IMAGE_URL#"registry.kube-system.svc.cluster.local"}
> export IMAGE_TAG=$(tkn pr describe --last -o jsonpath='{.spec.params[?(@.name=="imageTag")].value}')
> export DOCKER_IMG="${IMAGE_URL}:${IMAGE_TAG}"
> 
> ~
> ❯ crane ls "${IMAGE_URL}"
> 
> Error: reading tags for localhost:8888/citi/picalc: GET http://localhost:8888/v2/citi/picalc/tags/list?n=1000: NAME_UNKNOWN: repository name not known to registry; map[name:citi/picalc]
> 
> ~
> ❯ crane ls localhost:8888/citi/picalc
> 
> 
> Error: reading tags for localhost:8888/citi/picalc: GET http://localhost:8888/v2/citi/picalc/tags/list?n=1000: NAME_UNKNOWN: repository name not known to registry; map[name:citi/picalc]
> ```

Looks like something went wrong earlier in the process. Try the following to see what repositories you have in your registry:
```bash
crane catalog localhost:8888
```

If you doing see `citi/picalc`, you might want to retry from scratch.

**Comment by maorkuriel** [comment] 2021-12-16 14:39
No problem, I will start from scratch.

**Comment by maorkuriel** [comment] 2021-12-16 14:59
Running a clean slate ran with no issues, here is the output:
```
ssf on  main
❯ crane ls "${IMAGE_URL}"

sha256-ebb81f280b8459e63f3b483e96574af4b069da00b920806765f14a3f3aff60df.sig
1.0
sha256-ebb81f280b8459e63f3b483e96574af4b069da00b920806765f14a3f3aff60df.att

ssf on  main
❯ cosign verify --key k8s://tekton-chains/signing-secrets "${DOCKER_IMG}"


Verification for localhost:8888/citi/picalc:1.0 --
The following checks were performed on each of these signatures:
  - The cosign claims were validated
  - The signatures were verified against the specified public key
  - Any certificates were verified against the Fulcio roots.

[{"critical":{"identity":{"docker-reference":"registry.kube-system.svc.cluster.local/citi/picalc"},"image":{"docker-manifest-digest":"sha256:ebb81f280b8459e63f3b483e96574af4b069da00b920806765f14a3f3aff60df"},"type":"Tekton container signature"},"optional":{}}]

ssf on  main
❯ cosign verify-attestation --key k8s://tekton-chains/signing-secrets "${DOCKER_IMG}"


Verification for localhost:8888/citi/picalc:1.0 --
The following checks were performed on each of these signatures:
  - The cosign claims were validated
  - The signatures were verified against the specified public key
  - Any certificates were verified against the Fulcio roots.
{"payloadType":"application/vnd.in-toto+json","payload":"eyJfdHlwZSI6Imh0dHBzOi8vaW4tdG90by5pby9TdGF0ZW1lbnQvdjAuMSIsInByZWRpY2F0ZVR5cGUiOiJodHRwczovL3Rla3Rvbi5kZXYvY2hhaW5zL3Byb3ZlbmFuY2UiLCJzdWJqZWN0IjpbeyJuYW1lIjoicmVnaXN0cnkua3ViZS1zeXN0ZW0uc3ZjLmNsdXN0ZXIubG9jYWwvY2l0aS9waWNhbGMiLCJkaWdlc3QiOnsic2hhMjU2IjoiZWJiODFmMjgwYjg0NTllNjNmM2I0ODNlOTY1NzRhZjRiMDY5ZGEwMGI5MjA4MDY3NjVmMTRhM2YzYWZmNjBkZiJ9fV0sInByZWRpY2F0ZSI6eyJpbnZvY2F0aW9uIjp7InBhcmFtZXRlcnMiOlsiQ09OVEVYVD17c3RyaW5nIHNyYyBbXX0iLCJJTUFHRT17c3RyaW5nIHJlZ2lzdHJ5Lmt1YmUtc3lzdGVtLnN2Yy5jbHVzdGVyLmxvY2FsL2NpdGkvcGljYWxjOjEuMCBbXX0iLCJET0NLRVJGSUxFPS4vRG9ja2VyZmlsZSIsIkNPTlRFWFQ9Li8iLCJFWFRSQV9BUkdTPVtdIiwiQlVJTERFUl9JTUFHRT1nY3IuaW8va2FuaWtvLXByb2plY3QvZXhlY3V0b3I6djEuNS4xQHNoYTI1NjpjNjE2NjcxN2Y3ZmUwYjdkYTQ0OTA4Yzk4NjEzN2VjZmVhYjIxZjMxZWMzOTkyZjZlMTI4ZmZmOGE5NGJlOGE1Il0sInJlY2lwZV91cmkiOiJ0YXNrOi8va2FuaWtvLWNoYWlucyIsImV2ZW50X2lkIjoiZGYwYWNiMjQtNWIwNS00NjIxLWI1MmQtNGJkYTdiYTU4NGZlIiwiYnVpbGRlci5pZCI6InRla3Rvbi1jaGFpbnMifSwicmVjaXBlIjp7InN0ZXBzIjpbeyJlbnRyeVBvaW50Ijoic2V0IC1lXG5lY2hvIFwiRlJPTSBhbHBpbmVAc2hhMjU2OjY5ZTcwYTc5ZjJkNDFhYjVkNjM3ZGU5OGMxZTBiMDU1MjA2YmE0MGE4MTQ1ZTdiZGRiNTVjY2MwNGUxM2NmOGZcIiB8IHRlZSAkKHBhcmFtcy5ET0NLRVJGSUxFKVxuIiwiYXJndW1lbnRzIjpudWxsLCJlbnZpcm9ubWVudCI6eyJjb250YWluZXIiOiJhZGQtZG9ja2VyZmlsZSIsImltYWdlIjoiZG9ja2VyLXB1bGxhYmxlOi8vYmFzaEBzaGEyNTY6ODc2NjAwZjhhMWNlMDRkZjI3NzIyZjQ4MmViZmU2Njk2YWE0ZmVjNmE2MWE3ZWEyY2Y2ZDUwNDVhNjNjNWQ5YSJ9LCJhbm5vdGF0aW9ucyI6bnVsbH0seyJlbnRyeVBvaW50IjoiIiwiYXJndW1lbnRzIjpbIiQocGFyYW1zLkVYVFJBX0FSR1MpIiwiLS1kb2NrZXJmaWxlPSQocGFyYW1zLkRPQ0tFUkZJTEUpIiwiLS1jb250ZXh0PSQod29ya3NwYWNlcy5zb3VyY2UucGF0aCkvJChwYXJhbXMuQ09OVEVYVCkiLCItLWRlc3RpbmF0aW9uPSQocGFyYW1zLklNQUdFKSIsIi0tZGlnZXN0LWZpbGU9JChyZXN1bHRzLklNQUdFX0RJR0VTVC5wYXRoKSJdLCJlbnZpcm9ubWVudCI6eyJjb250YWluZXIiOiJidWlsZC1hbmQtcHVzaCIsImltYWdlIjoiZG9ja2VyLXB1bGxhYmxlOi8vZ2NyLmlvL2thbmlrby1wcm9qZWN0L2V4ZWN1dG9yQHNoYTI1NjpkYzdhZjI0MTZmNGM0YThmN2RmYWI3ZTJlZTU2NGEwNThhOWIwOGQzMzA4ZmUxNGMyNmYxMTdiZjJiMDA2ZjQ5In0sImFubm90YXRpb25zIjpudWxsfSx7ImVudHJ5UG9pbnQiOiJzZXQgLWVcbmVjaG8gJChwYXJhbXMuSU1BR0UpIHwgdGVlICQocmVzdWx0cy5JTUFHRV9VUkwucGF0aClcbiIsImFyZ3VtZW50cyI6bnVsbCwiZW52aXJvbm1lbnQiOnsiY29udGFpbmVyIjoid3JpdGUtdXJsIiwiaW1hZ2UiOiJkb2NrZXItcHVsbGFibGU6Ly9iYXNoQHNoYTI1Njo4NzY2MDBmOGExY2UwNGRmMjc3MjJmNDgyZWJmZTY2OTZhYTRmZWM2YTYxYTdlYTJjZjZkNTA0NWE2M2M1ZDlhIn0sImFubm90YXRpb25zIjpudWxsfV19LCJtZXRhZGF0YSI6eyJidWlsZFN0YXJ0ZWRPbiI6IjIwMjEtMTItMTZUMTQ6NTU6MTRaIiwiYnVpbGRGaW5pc2hlZE9uIjoiMjAyMS0xMi0xNlQxNDo1NTozN1oifX19","signatures":[{"keyid":"SHA256:9gK+vo+SDOuKA5bKeZpDjwxjmWnbX1Yak0vHY8Dn8yk","sig":"MEUCIH9gprtlNDswzMCK1HirS6PjrZ3tcgQvVLiWIfo0laSfAiEAhZc6Se1A0jYZpgr4giwtERVzUirOSmuAWAWF/cMsinI="}]}

ssf on  main
```

Thanks @bradbeck

**Comment by bradbeck** [comment] 2021-12-16 15:02
@anniepamela2020 Are you still experiencing this problem? If not, is it ok to close this issue?

**Comment by anniepamela2020** [comment] 2021-12-16 19:25
yes we can close the issue

**Closed** 2021-12-16 19:26 UTC
Labels: bug
