### ISSUE TITLE
Kyverno Pod is crashing

### ISSUE THREAD

**Issue by maorkuriel** [thesecuresoftwarefactory/ssf#102] opened 2021-12-12 12:28 UTC
I tried to run a non-signed image and I was successful.
I noticed that kyverno is not running, I ran kubectl get pods --all-namespaces.
kyverno            kyverno-84d959479f-wx9fn                          0/1     CrashLoopBackOff   7 (2m ago)   15m

Current Behavior
----------------
The kyverno deployment is not running and the pods is crashing

Expected Behavior
-----------------
The pod is deployed and the policy engine will block non signed images from being deployed in the k8s cluster

 

Steps to Reproduce
------------------

I followed the SSF documentation steps by step.

Your Environment
----------------

Last commit:
  f529840 Use checksum validation in vendorme for kyverno (#95)  (HEAD -> main, origin/main, origin/HEAD)
Kubernetes:
  Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.0", GitCommit:"ab69524f795c42094a6630298ff53f3c3ebab7f4", GitTreeState:"clean", BuildDate:"2021-12-07T18:08:39Z", GoVersion:"go1.17.3", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-27T18:35:25Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/arm64"}
Tekton:
  Client version: 0.21.0
Pipeline version: v0.29.0
Dashboard version: v0.22.0

Log Files
----------------

❯ kubectl logs kyverno-84d959479f-wx9fn -n kyverno
I1212 12:16:06.574580       1 version.go:17]  "msg"="Kyverno"  "Version"="v1.5.0-rc1-130-g8a0d465d"
I1212 12:16:06.575444       1 version.go:18]  "msg"="Kyverno"  "BuildHash"="main/8a0d465d9084963f5d84603633215bbb82f8a645"
I1212 12:16:06.575541       1 version.go:19]  "msg"="Kyverno"  "BuildTime"="2021-11-19_11:10:45AM"
I1212 12:16:06.577600       1 config.go:104] CreateClientConfig "msg"="Using in-cluster configuration"
I1212 12:16:06.669674       1 util.go:97]  "msg"="CRD found"  "gvr"="kyverno.io/v1, Resource=clusterpolicies"
I1212 12:16:06.670716       1 util.go:97]  "msg"="CRD found"  "gvr"="wgpolicyk8s.io/v1alpha2, Resource=clusterpolicyreports"
I1212 12:16:06.671592       1 util.go:97]  "msg"="CRD found"  "gvr"="wgpolicyk8s.io/v1alpha2, Resource=policyreports"
I1212 12:16:06.672375       1 util.go:97]  "msg"="CRD found"  "gvr"="kyverno.io/v1alpha2, Resource=clusterreportchangerequests"
I1212 12:16:06.673228       1 util.go:97]  "msg"="CRD found"  "gvr"="kyverno.io/v1alpha2, Resource=reportchangerequests"
I1212 12:16:07.086675       1 main.go:174] setup "msg"="initializing registry credentials"  "secrets"=["regcred"]
I1212 12:16:07.115667       1 dynamicconfig.go:150] ConfigData "msg"="init configuration from commandline arguments for filterK8sResources"
I1212 12:16:07.119762       1 dynamicconfig.go:330] ConfigData "msg"="Init resource filters"  "filters"=[{"Kind":"Event","Namespace":"*","Name":"*"},{"Kind":"*","Namespace":"kube-system","Name":"*"},{"Kind":"*","Namespace":"kube-public","Name":"*"},{"Kind":"*","Namespace":"kube-node-lease","Name":"*"},{"Kind":"Node","Namespace":"*","Name":"*"},{"Kind":"APIService","Namespace":"*","Name":"*"},{"Kind":"TokenReview","Namespace":"*","Name":"*"},{"Kind":"SubjectAccessReview","Namespace":"*","Name":"*"},{"Kind":"*","Namespace":"kyverno","Name":"*"},{"Kind":"Binding","Namespace":"*","Name":"*"},{"Kind":"ReplicaSet","Namespace":"*","Name":"*"},{"Kind":"ReportChangeRequest","Namespace":"*","Name":"*"},{"Kind":"ClusterReportChangeRequest","Namespace":"*","Name":"*"},{"Kind":"PolicyReport","Namespace":"*","Name":"*"},{"Kind":"ClusterPolicyReport","Namespace":"*","Name":"*"}]
I1212 12:16:07.120017       1 dynamicconfig.go:341] ConfigData "msg"="Init resource "  "excludeRoles"=""
I1212 12:16:07.126937       1 metrics.go:139] MetricsConfig "msg"="Configuring metrics refresh at a periodic rate of 24h0m0s"
I1212 12:16:07.128303       1 main.go:284] setup "msg"="enabling metrics service"  "address"=":8000"
I1212 12:16:07.138521       1 leaderelection.go:243] attempting to acquire leader lease kyverno/webhook-register...
I1212 12:16:07.146317       1 leaderelection.go:112] webhookRegister/LeaderElection "msg"="another instance has been elected as leader" "current id"="kyverno-84d959479f-wx9fn_457fc550-8a17-4948-9109-87588e5a7653" "leader"="kyverno-84d959479f-wx9fn_d8b409a2-7034-4a1e-a77f-15de9cd1c2f2"
E1212 12:16:09.957136       1 crdSync.go:169]  "msg"="could not parse crd schema" "error"="crd schema has no properties"  "name"="ClusterTask"
E1212 12:16:09.958257       1 crdSync.go:169]  "msg"="could not parse crd schema" "error"="crd schema has no properties"  "name"="Condition"
E1212 12:16:09.959487       1 crdSync.go:169]  "msg"="could not parse crd schema" "error"="crd schema has no properties"  "name"="Extension"
E1212 12:16:09.966335       1 crdSync.go:169]  "msg"="could not parse crd schema" "error"="crd schema has no properties"  "name"="PipelineResource"
E1212 12:16:09.968243       1 crdSync.go:169]  "msg"="could not parse crd schema" "error"="crd schema has no properties"  "name"="PipelineRun"
E1212 12:16:09.969755       1 crdSync.go:169]  "msg"="could not parse crd schema" "error"="crd schema has no properties"  "name"="Pipeline"
E1212 12:16:10.054840       1 crdSync.go:169]  "msg"="could not parse crd schema" "error"="crd schema has no properties"  "name"="Run"
E1212 12:16:10.056744       1 crdSync.go:169]  "msg"="could not parse crd schema" "error"="crd schema has no properties"  "name"="TaskRun"
E1212 12:16:10.058243       1 crdSync.go:169]  "msg"="could not parse crd schema" "error"="crd schema has no properties"  "name"="Task"
E1212 12:16:10.339812       1 crdSync.go:169]  "msg"="could not parse crd schema" "error"="crd schema has no properties"  "name"="ClusterTask"
E1212 12:16:10.341030       1 crdSync.go:169]  "msg"="could not parse crd schema" "error"="crd schema has no properties"  "name"="Condition"
E1212 12:16:10.342246       1 crdSync.go:169]  "msg"="could not parse crd schema" "error"="crd schema has no properties"  "name"="Extension"
E1212 12:16:10.348792       1 crdSync.go:169]  "msg"="could not parse crd schema" "error"="crd schema has no properties"  "name"="PipelineResource"
E1212 12:16:10.350730       1 crdSync.go:169]  "msg"="could not parse crd schema" "error"="crd schema has no properties"  "name"="PipelineRun"
E1212 12:16:10.352313       1 crdSync.go:169]  "msg"="could not parse crd schema" "error"="crd schema has no properties"  "name"="Pipeline"
E1212 12:16:10.446385       1 crdSync.go:169]  "msg"="could not parse crd schema" "error"="crd schema has no properties"  "name"="Run"
E1212 12:16:10.448291       1 crdSync.go:169]  "msg"="could not parse crd schema" "error"="crd schema has no properties"  "name"="TaskRun"
E1212 12:16:10.449744       1 crdSync.go:169]  "msg"="could not parse crd schema" "error"="crd schema has no properties"  "name"="Task"
I1212 12:16:11.075027       1 certmanager.go:107] CertManager "msg"="read TLS pem pair from the secret"
I1212 12:16:11.084134       1 reportrequest.go:178] ReportChangeRequestGenerator "msg"="start"
I1212 12:16:11.084650       1 informer.go:109] PolicyCacheController "msg"="starting"
I1212 12:16:11.085134       1 leaderelection.go:243] attempting to acquire leader lease kyverno/kyverno...
I1212 12:16:11.085389       1 controller.go:118] EventGenerator "msg"="start"
I1212 12:16:11.096542       1 leaderelection.go:112] kyverno/LeaderElection "msg"="another instance has been elected as leader" "current id"="kyverno-84d959479f-wx9fn_4b73373d-7a52-488a-aa83-4d02d217e465" "leader"="kyverno-84d959479f-wx9fn_242f3af8-6a4b-4c58-8984-fdda816b69b9"
I1212 12:16:11.286664       1 server.go:581] WebhookServer "msg"="starting service"
I1212 12:16:23.124254       1 leaderelection.go:253] successfully acquired lease kyverno/webhook-register
I1212 12:16:23.124978       1 leaderelection.go:93] webhookRegister/LeaderElection "msg"="started leading" "id"="kyverno-84d959479f-wx9fn_457fc550-8a17-4948-9109-87588e5a7653"
I1212 12:16:23.141387       1 certRenewer.go:78] CertRenewer/InitTLSPemPair "msg"="using existing TLS key/certificate pair"
E1212 12:16:23.148759       1 registration.go:226] Register/ValidateWebhookConfigurations "msg"="unable to fetch ConfigMap" "error"="configmaps \"init-config\" not found"  "name"="init-config" "namespace"="kyverno"
I1212 12:16:24.164958       1 registration.go:641] Register "msg"="Endpoint ready"  "name"="kyverno-svc" "ns"="kyverno"
panic: runtime error: index out of range [0] with length 0

goroutine 1056 [running]:
github.com/kyverno/kyverno/pkg/webhookconfig.(*Register).GetKubePolicyClusterRoleName(0xc00021c930)
	C:/Users/jim/go/src/github.com/JimBugwadia/kyverno/pkg/webhookconfig/common.go:83 +0x172
github.com/kyverno/kyverno/pkg/webhookconfig.(*Register).constructOwner(0xc000cc9a80)
	C:/Users/jim/go/src/github.com/JimBugwadia/kyverno/pkg/webhookconfig/common.go:63 +0x6a
github.com/kyverno/kyverno/pkg/webhookconfig.(*Register).constructVerifyMutatingWebhookConfig(0xc00021c930, {0xc00143b680, 0x432, 0x432})
	C:/Users/jim/go/src/github.com/JimBugwadia/kyverno/pkg/webhookconfig/registration.go:493 +0x4e
github.com/kyverno/kyverno/pkg/webhookconfig.(*Register).createVerifyMutatingWebhookConfiguration(0xc00021c930, {0xc00143b680, 0x1, 0x10})
	C:/Users/jim/go/src/github.com/JimBugwadia/kyverno/pkg/webhookconfig/registration.go:377 +0x4c
github.com/kyverno/kyverno/pkg/webhookconfig.(*Register).Register(0xc00021c930)
	C:/Users/jim/go/src/github.com/JimBugwadia/kyverno/pkg/webhookconfig/registration.go:106 +0x1b6
github.com/kyverno/kyverno/pkg/common.RetryFunc.func1()
	C:/Users/jim/go/src/github.com/JimBugwadia/kyverno/pkg/common/common.go:135 +0x17d
main.main.func3()
	C:/Users/jim/go/src/github.com/JimBugwadia/kyverno/cmd/kyverno/main.go:404 +0x127
github.com/kyverno/kyverno/pkg/leaderelection.New.func1({0x0, 0x0})
	C:/Users/jim/go/src/github.com/JimBugwadia/kyverno/pkg/leaderelection/leaderelection.go:96 +0xf5
created by k8s.io/client-go/tools/leaderelection.(*LeaderElector).Run
	C:/Users/jim/go/pkg/mod/k8s.io/client-go@v0.21.4/tools/leaderelection/leaderelection.go:207 +0x154

**Comment by mlieberman85** [comment] 2021-12-13 04:05
How are you installing the SSF?

**Comment by mlieberman85** [comment] 2021-12-13 04:06
Also, where are you running kubernetes? Are you using kind, minikube, something in the cloud?

**Comment by maorkuriel** [comment] 2021-12-13 09:32
I am running minikube on my Macbook pro M1

I followed the steps from the SSF docs - https://thesecuresoftwarefactory.github.io/ssf/docs/getting-started/quick-start/

**Comment by joshualucas84** [comment] 2021-12-13 14:51
I can confirm I'm seeing the same issue,
 
@pxp928, @mlieberman85  looking at this error im wondering if this is coming from jim's patched container

ghcr.io/jimbugwadia/kyverno:v1.6.0-130-g8a0d465d



![image](https://user-images.githubusercontent.com/5225184/145833929-8d8fea4b-c8d4-4a4a-b13d-5fd19ed57b98.png)

**Comment by bradbeck** [comment] 2021-12-13 14:55
I'm also able to reproduce this with minikube on my MacBook Pro M1.

**Comment by mlieberman85** [comment] 2021-12-13 14:56
Interesting. You're not on an m1 mac right looking at your screenshot @joshualucas84. I'm not seeing this issue so let me see if there's something else going on.

**Comment by bradbeck** [comment] 2021-12-13 15:11
I’m seeing it on commit f529840d but not on the previous commit caaa1f94

**Comment by pxp928** [comment] 2021-12-13 15:15
We recently implemented the vendor for kyverno. I wonder if that went back a version?

**Comment by mlieberman85** [comment] 2021-12-13 15:27
@pxp928 I looked through the vendored code. Kyverno doesn't actually pin to an image version meaning we pull down the latest image each time regardless. We should talk to Kyverno folks to pin it to the SHA or otherwise have the vendoring mechanism on our side also modify or patch the k8s config to pin to specific image digests.

**Comment by bradbeck** [comment] 2021-12-13 15:29
Looks like the 1 line change in the YAML file between f529840 and caaa1f9 makes all the difference:
```
    app.kubernetes.io/ownerreference: "true"
```

**Comment by bradbeck** [comment] 2021-12-13 16:03
Looks like the YAML file change was introduce in https://github.com/kyverno/kyverno/pull/2776, but there are also more recent changes to that file in https://github.com/kyverno/kyverno/pull/2799

**Comment by bradbeck** [comment] 2021-12-13 16:16
The latest version of `install.yaml` also seems to fail to start:
https://github.com/kyverno/kyverno/blob/edafffd2bd5993661e9795ce62074bd4dd630f04/config/install.yaml

**Comment by bradbeck** [comment] 2021-12-13 16:32
Resolved by #103

**Closed by bradbeck** 2021-12-13 16:32 UTC
Labels: bug
